In [1]:
import pandas as pd

data_2015 = pd.read_csv('https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-114842/valeursfoncieres-2015.txt', sep="|")
data_2015

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (18,23,24,26,28,30,31,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

         Code service CH  ...  Surface terrain
0                    NaN  ...             82.0
1                    NaN  ...           1550.0
2                    NaN  ...              4.0
3                    NaN  ...            298.0
4                    NaN  ...            195.0
...                  ...  ...              ...
2750300              NaN  ...              NaN
2750301              NaN  ...              NaN
2750302              NaN  ...              NaN
2750303              NaN  ...              NaN
2750304              NaN  ...              NaN

[2750305 rows x 43 columns]

In [0]:
data_marseille = data_2015[data_2015['Commune'].str.contains("MARSEILLE", na=False)]

In [6]:
data_marseille['Commune'].value_counts()

MARSEILLE 8EME             3108
MARSEILLE 9EME             2501
MARSEILLE 13EME            2211
MARSEILLE 5EME             1801
MARSEILLE 10EME            1763
MARSEILLE 12EME            1724
MARSEILLE 6EME             1655
MARSEILLE 11EME            1634
MARSEILLE 4EME             1544
MARSEILLE 15EME            1305
MARSEILLE 1ER              1274
MARSEILLE 3EME             1263
MARSEILLE 7EME             1173
MARSEILLE 2EME             1114
MARSEILLE 14EME             971
MARSEILLE 16EME             435
MARSEILLE-LES-AUBIGNY        58
MARSEILLETTE                 57
MARSEILLE EN BEAUVAISIS      34
Name: Commune, dtype: int64

In [0]:
marseille_list_arrondissement = ['MARSEILLE 8EME',
'MARSEILLE 9EME',
'MARSEILLE 13EME',
'MARSEILLE 5EME',
'MARSEILLE 10EME',
'MARSEILLE 12EME',
'MARSEILLE 6EME',
'MARSEILLE 11EME',
'MARSEILLE 4EME',
'MARSEILLE 15EME',
'MARSEILLE 1ER',
'MARSEILLE 3EME',
'MARSEILLE 7EME',
'MARSEILLE 2EME',
'MARSEILLE 14EME',
'MARSEILLE 16EME']

In [27]:
data_marseille = data_2015[data_2015['Commune'].isin(marseille_list_arrondissement)]
data_marseille.head()

        Code service CH  ...  Surface terrain
245197              NaN  ...              NaN
245198              NaN  ...              NaN
245199              NaN  ...              NaN
245200              NaN  ...              NaN
245201              NaN  ...              NaN

[5 rows x 43 columns]

In [10]:
data_marseille.Commune.value_counts()

MARSEILLE 8EME     3108
MARSEILLE 9EME     2501
MARSEILLE 13EME    2211
MARSEILLE 5EME     1801
MARSEILLE 10EME    1763
MARSEILLE 12EME    1724
MARSEILLE 6EME     1655
MARSEILLE 11EME    1634
MARSEILLE 4EME     1544
MARSEILLE 15EME    1305
MARSEILLE 1ER      1274
MARSEILLE 3EME     1263
MARSEILLE 7EME     1173
MARSEILLE 2EME     1114
MARSEILLE 14EME     971
MARSEILLE 16EME     435
Name: Commune, dtype: int64

In [11]:
print('Shape: ',data_marseille.shape)

(25476, 43)

In [28]:
data_marseille.isnull().sum()

Code service CH               25476
Reference document            25476
1 Articles CGI                25476
2 Articles CGI                25476
3 Articles CGI                25476
4 Articles CGI                25476
5 Articles CGI                25476
No disposition                    0
Date mutation                     0
Nature mutation                   0
Valeur fonciere                   1
No voie                        3125
B/T/Q                         24234
Type de voie                   1166
Code voie                       603
Voie                            603
Code postal                     603
Commune                           0
Code departement                  0
Code commune                      0
Prefixe de section                0
Section                           0
No plan                           0
No Volume                     25421
1er lot                        4247
Surface Carrez du 1er lot     21134
2eme lot                      21444
Surface Carrez du 2eme lot    24339
3eme lot                      25083
Surface Carrez du 3eme lot    25433
4eme lot                      25306
Surface Carrez du 4eme lot    25457
5eme lot                      25405
Surface Carrez du 5eme lot    25475
Nombre de lots                    0
Code type local                3241
Type local                     3241
Identifiant local             25476
Surface reelle bati            3252
Nombre pieces principales      3252
Nature culture                21264
Nature culture speciale       25476
Surface terrain               21264
dtype: int64

In [29]:
data_marseille = data_marseille.drop(['Code service CH','Reference document','1 Articles CGI','2 Articles CGI',
                                      '3 Articles CGI','4 Articles CGI','5 Articles CGI','Identifiant local','No Volume','B/T/Q',
                                      'Surface Carrez du 1er lot','2eme lot','Surface Carrez du 2eme lot','3eme lot',
                                      'Surface Carrez du 3eme lot','4eme lot','Surface Carrez du 4eme lot','5eme lot',
                                      'Surface Carrez du 5eme lot','Nature culture','Nature culture speciale','Surface terrain'], axis=1)
data_marseille.isnull().sum()

No disposition                  0
Date mutation                   0
Nature mutation                 0
Valeur fonciere                 1
No voie                      3125
Type de voie                 1166
Code voie                     603
Voie                          603
Code postal                   603
Commune                         0
Code departement                0
Code commune                    0
Prefixe de section              0
Section                         0
No plan                         0
1er lot                      4247
Nombre de lots                  0
Code type local              3241
Type local                   3241
Surface reelle bati          3252
Nombre pieces principales    3252
dtype: int64

In [21]:
data_marseille.shape

(25476, 35)

In [6]:
%time 

#lien data gouv https://www.data.gouv.fr/en/datasets/demandes-de-valeurs-foncieres/
#faq https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20191030-171734/faq.pdf
#dictionnaire de données https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20191220-102114/notice-descriptive-du-fichier-dvf.pdf
import pandas as pd
from tqdm.notebook import tqdm

url_dict = {
    '2019':'https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-115822/valeursfoncieres-2019.txt',
    '2018':'https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-115643/valeursfoncieres-2018.txt',
    '2017':'https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-115446/valeursfoncieres-2017.txt',
    '2016':'https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-115256/valeursfoncieres-2016.txt',
    '2015':'https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20200416-114842/valeursfoncieres-2015.txt'
}
def get_subsample():
    data_all_year=[]
    for year,url in tqdm(url_dict.items()):
        print(f'----------STARTING YEAR {year}----------')
        data_ = pd.read_csv(url, sep="|")
        data_ = data_.drop(['Code service CH','Reference document','1 Articles CGI','2 Articles CGI',
                                      '3 Articles CGI','4 Articles CGI','5 Articles CGI','Identifiant local','No Volume','B/T/Q',
                                      'Surface Carrez du 1er lot','2eme lot','Surface Carrez du 2eme lot','3eme lot',
                                      'Surface Carrez du 3eme lot','4eme lot','Surface Carrez du 4eme lot','5eme lot',
                                      'Surface Carrez du 5eme lot','Nature culture','Nature culture speciale','Surface terrain'], axis=1)
        
        print('Shape from import: ',data_.shape)

        marseille_list_arrondissement = ['MARSEILLE 8EME','MARSEILLE 9EME','MARSEILLE 13EME','MARSEILLE 5EME',
                                         'MARSEILLE 10EME','MARSEILLE 12EME','MARSEILLE 6EME','MARSEILLE 11EME',
                                         'MARSEILLE 4EME','MARSEILLE 15EME','MARSEILLE 1ER','MARSEILLE 3EME',
                                         'MARSEILLE 7EME','MARSEILLE 2EME','MARSEILLE 14EME','MARSEILLE 16EME']

        data_marseille = data_[data_['Commune'].isin(marseille_list_arrondissement)]
        print('Shape after subsample: ',data_marseille.shape)
        print(f'\n Sampling of {round((data_marseille.shape[0]/data_.shape[0])*100,2)} % of the original dataframe \n')
        del data_
        data_marseille['year'] = year
        data_all_year.append(data_marseille)
        del data_marseille
        print(f'----------YEAR {year} DONE---------- \n')
        
    print('STARTING CONCATENATING')
    df = pd.concat(data_all_year)
    print('CONCATENING DONE')
    return df

df = get_subsample()

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs

HBox(children=(IntProgress(value=0, max=5), HTML(value='')))

----------STARTING YEAR 2019----------

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (18,23,24,26,28,29,31,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Shape from import:  (2535791, 21)
Shape after subsample:  (30855, 21)

 Sampling of 1.22 % of the original dataframe

----------YEAR 2019 DONE----------

----------STARTING YEAR 2018----------

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (14,18,23,24,26,28,31,32,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Shape from import:  (3277682, 21)
Shape after subsample:  (30989, 21)

 Sampling of 0.95 % of the original dataframe

----------YEAR 2018 DONE----------

----------STARTING YEAR 2017----------

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (18,23,24,26,28,31,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Shape from import:  (3378135, 21)
Shape after subsample:  (35618, 21)

 Sampling of 1.05 % of the original dataframe

----------YEAR 2017 DONE----------

----------STARTING YEAR 2016----------

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (18,23,24,26,28,30,31,32,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Shape from import:  (2938560, 21)
Shape after subsample:  (28187, 21)

 Sampling of 0.96 % of the original dataframe

----------YEAR 2016 DONE----------

----------STARTING YEAR 2015----------

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (18,23,24,26,28,30,31,33,41) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Shape from import:  (2750305, 21)
Shape after subsample:  (25476, 21)

 Sampling of 0.93 % of the original dataframe

----------YEAR 2015 DONE----------


STARTING CONCATENATING
CONCATENING DONE

In [7]:
%time

df.head()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.72 µs

        No disposition Date mutation  ... Nombre pieces principales  year
214737               1    04/01/2019  ...                       NaN  2019
214738               1    04/01/2019  ...                       NaN  2019
214739               1    04/01/2019  ...                       3.0  2019
214740               1    04/01/2019  ...                       3.0  2019
214741               1    03/01/2019  ...                       0.0  2019

[5 rows x 22 columns]

In [8]:
df.shape

(151125, 22)

In [0]:
df.to_csv('df_marseille_dvf.csv', index=False, sep="|")

In [9]:
print(data_all_year)

None

In [0]:
from google.colab import files
files.download("df_marseille_dvf.csv")